#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$(dirname "$0")/config"

if ! docker images | grep -e "^$PLUGIN_IMAGE " | grep -q "$PLUGIN_IMAGE_VERSION" ; then
  docker pull "$PLUGIN_IMAGE:$PLUGIN_IMAGE_VERSION"
fi

if ! docker images | grep -e "^svendowideit/ambassador "; then
  docker pull svendowideit/ambassador:latest
fi

if ! docker images | grep -e "^aanand/wait "; then
  docker pull aanand/wait:latest
fi

mkdir -p "$PLUGIN_DATA_ROOT" || echo "Failed to create $PLUGIN_SERVICE directory"
chown dokku:dokku "$PLUGIN_DATA_ROOT"
