#!/usr/bin/env bash
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

plugin-post-app-clone-setup() {
  "${DOKKU_LIB_ROOT}/data/${PLUGIN_COMMAND_PREFIX}/dokku-datastore" trigger-post-app-clone-setup "$PLUGIN_COMMAND_PREFIX" "$@"
}

plugin-post-app-clone-setup "$@"
