#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

service-app-links-cmd() {
  declare desc="list all $PLUGIN_SERVICE service links for a given app"
  local cmd="$PLUGIN_COMMAND_PREFIX:app-links" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1

  "${DOKKU_LIB_ROOT}/data/${PLUGIN_COMMAND_PREFIX}/dokku-datastore" app-links "$PLUGIN_COMMAND_PREFIX" "$@"
}

service-app-links-cmd "$@"
