#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_BASE_PATH/common/functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/functions"

service-backup-schedule-cat-cmd() {
  #E cat the contents of the configured backup cronfile for the service
  #E dokku $PLUGIN_COMMAND_PREFIX:backup-schedule-cat lolipop
  #A service, service to run command against
  declare desc="cat the contents of the configured backup cronfile for the service"
  local cmd="$PLUGIN_COMMAND_PREFIX:backup-schedule-cat" argv=("$@"); [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare SERVICE="$1"

  [[ -z "$SERVICE" ]] && dokku_log_fail "Please specify a name for the service"
  verify_service_name "$SERVICE"
  service_backup_schedule_cat "$SERVICE"
}

service-backup-schedule-cat-cmd "$@"
