#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

service-backup-logs-cmd() {
  declare desc="print the most recent output of the scheduled backups of the service"
  local cmd="$PLUGIN_COMMAND_PREFIX:backup-logs" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1

  "${DOKKU_LIB_ROOT}/data/${PLUGIN_COMMAND_PREFIX}/dokku-datastore" backup-logs "$PLUGIN_COMMAND_PREFIX" "$@"
}

service-backup-logs-cmd "$@"
