#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

service-backup-schedule-cat-cmd() {
  declare desc="cat the contents of the configured backup cronfile for the service"
  local cmd="$PLUGIN_COMMAND_PREFIX:backup-schedule-cat" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1

  "${DOKKU_LIB_ROOT}/data/${PLUGIN_COMMAND_PREFIX}/dokku-datastore" backup-schedule-cat "$PLUGIN_COMMAND_PREFIX" "$@"
}

service-backup-schedule-cat-cmd "$@"
