#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_BASE_PATH/common/functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/functions"

service-destroy-database-cmd() {
  declare desc="delete a $PLUGIN_SERVICE database from the specified service"
  local cmd="$PLUGIN_COMMAND_PREFIX:destroy-database" argv=("$@"); [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare SERVICE="$1" DATABASE="$2"

  [[ -z "$SERVICE" ]] && dokku_log_fail "Please specify a name for the service"
  [[ -z "$DATABASE" ]] && dokku_log_fail "Please specify a name for the database"
  verify_service_name "$SERVICE"
  verify_database_name "$SERVICE" "$DATABASE"
  SERVICE_ROOT="$PLUGIN_DATA_ROOT/$SERVICE"
  SERVICE_NAME="$(get_service_name "$SERVICE")"

  dokku_log_info1 "Deleting $DATABASE from $SERVICE"
  if docker exec "$SERVICE_NAME" su - postgres -c "psql -c \"DROP DATABASE $DATABASE;\"" 2> /dev/null && docker exec "$SERVICE_NAME" su - postgres -c "psql -c \"DROP USER $DATABASE;\"" 2> /dev/null; then
    rm -f "$SERVICE_ROOT/databases/$DATABASE"
    rm -f "$SERVICE_ROOT/auth/$DATABASE"
    dokku_log_info2 "$PLUGIN_SERVICE $SERVICE database deleted: $DATABASE"
  else
    dokku_log_fail "Could not delete the database"
  fi
}

service-destroy-database-cmd "$@"
