#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_BASE_PATH/common/functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/functions"

service-destroy-database-cmd() {
  declare desc="delete a $PLUGIN_SERVICE database from the specified service"
  local cmd="$PLUGIN_COMMAND_PREFIX:destroy-database" argv=("$@"); [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare SERVICE="$1" DATABASE="$2"

  [[ -z "$SERVICE" ]] && dokku_log_fail "Please specify a name for the service"
  [[ -z "$DATABASE" ]] && dokku_log_fail "Please specify a name for the database"

  service_destroy_database "$SERVICE" "$DATABASE"
}

service-destroy-database-cmd "$@"
