#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

service-exists-cmd() {
  declare desc="check if the $PLUGIN_SERVICE service exists"
  local cmd="$PLUGIN_COMMAND_PREFIX:exists" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1

  "${DOKKU_LIB_ROOT}/data/${PLUGIN_COMMAND_PREFIX}/dokku-datastore" exists "$PLUGIN_COMMAND_PREFIX" "$@"
}

service-exists-cmd "$@"
