#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_BASE_PATH/common/functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/functions"

service-import-cmd() {
  #E import a datastore dump
  #E dokku $PLUGIN_COMMAND_PREFIX:import lolipop < database.dump
  #A service, service to run command against
  declare desc="import a dump into the $PLUGIN_SERVICE service database"
  local cmd="$PLUGIN_COMMAND_PREFIX:import" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare SERVICE="$1"
  is_implemented_command "$cmd" || dokku_log_fail "Not yet implemented"

  [[ -z "$SERVICE" ]] && dokku_log_fail "Please specify a valid name for the service"
  verify_service_name "$SERVICE"
  service_import "$SERVICE"
}

service-import-cmd "$@"
