#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

service-linked-cmd() {
  declare desc="check if the $PLUGIN_SERVICE service is linked to an app"
  local cmd="$PLUGIN_COMMAND_PREFIX:linked" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1

  "${DOKKU_LIB_ROOT}/data/${PLUGIN_COMMAND_PREFIX}/dokku-datastore" linked "$PLUGIN_COMMAND_PREFIX" "$@"
}

service-linked-cmd "$@"
