#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

service-links-cmd() {
  declare desc="list all apps linked to the $PLUGIN_SERVICE service"
  local cmd="$PLUGIN_COMMAND_PREFIX:links" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  local SERVICE_ROOT="$PLUGIN_DATA_ROOT/$SERVICE"
  local LINKS_FILE="$SERVICE_ROOT/LINKS"

  "${DOKKU_LIB_ROOT}/data/${PLUGIN_COMMAND_PREFIX}/dokku-datastore" links "$PLUGIN_COMMAND_PREFIX" "$@"
}

service-links-cmd "$@"
