#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_BASE_PATH/common/functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/functions"

postgres-link-cmd() {
  declare desc="link the $PLUGIN_SERVICE service to the app"
  local cmd="$PLUGIN_COMMAND_PREFIX:link" argv=("$@"); [[ ${argv[0]} == "$cmd" ]] && shift 1

  local USER=''

  local next_index=1; local skip=false; local args=("$@"); local positional=()
  for arg in "$@"; do
    $skip && skip=false && local next_index=$(( next_index + 1 )) && continue
    case "$arg" in
      --user)
        USER=${args[$next_index]}; skip=true
        ;;
      --database)
        DATABASE=${args[$next_index]}; skip=true
        ;;
      *)
        positional+=("$arg")
    esac
    local next_index=$(( next_index + 1 ))
  done

  declare SERVICE="${positional[0]}" APP="${positional[1]}"
  APP=${APP:="$DOKKU_APP_NAME"}

  [[ -z "$SERVICE" ]] && dokku_log_fail "Please specify a name for the service"
  [[ -z "$APP" ]] && dokku_log_fail "Please specify an app to run the command on"
  verify_app_name "$APP"
  verify_service_name "$SERVICE"
  [[ -z "$USER" ]] || verify_user_name "$SERVICE" "$USER"
  [[ -z "$DATABASE" ]] || verify_database_name "$SERVICE" "$DATABASE"
  service_link "$SERVICE" "$APP" "$USER" "$DATABASE"
}

postgres-link-cmd "$@"
