#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_BASE_PATH/common/functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/functions"

service-pause-cmd() {
  #E pause the running container for the service
  #E dokku $PLUGIN_COMMAND_PREFIX:pause lollipop
  #A service, service to run command against
  declare desc="pause a running $PLUGIN_SERVICE service"
  local cmd="$PLUGIN_COMMAND_PREFIX:pause" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare SERVICE="$1"

  [[ -z "$SERVICE" ]] && dokku_log_fail "Please specify a valid name for the service"
  verify_service_name "$SERVICE"
  service_pause "$SERVICE"
}

service-pause-cmd "$@"
