#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

service-reexpose-cmd() {
  declare desc="reexpose a $PLUGIN_SERVICE service, applying its expose settings"
  local cmd="$PLUGIN_COMMAND_PREFIX:reexpose" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1

  "${DOKKU_LIB_ROOT}/data/${PLUGIN_COMMAND_PREFIX}/dokku-datastore" reexpose "$PLUGIN_COMMAND_PREFIX" "$@"
}

service-reexpose-cmd "$@"
