#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

service-start-cmd() {
  declare desc="start a previously stopped $PLUGIN_SERVICE service"
  local cmd="$PLUGIN_COMMAND_PREFIX:start" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1

  "${DOKKU_LIB_ROOT}/data/${PLUGIN_COMMAND_PREFIX}/dokku-datastore" start "$PLUGIN_COMMAND_PREFIX" "$@"
}

service-start-cmd "$@"
