#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

service-stop-cmd() {
  declare desc="stop a running $PLUGIN_SERVICE service"
  local cmd="$PLUGIN_COMMAND_PREFIX:stop" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1

  "${DOKKU_LIB_ROOT}/data/${PLUGIN_COMMAND_PREFIX}/dokku-datastore" stop "$PLUGIN_COMMAND_PREFIX" "$@"
}

service-stop-cmd "$@"
