#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_BASE_PATH/common/functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/functions"

postgres-unexpose-cmd() {
  [[ -z $2 ]] && dokku_log_fail "Please specify a name for the service"
  verify_service_name "$2"
  service_port_unexpose "$2"
}

postgres-unexpose-cmd "$@"
