#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

service-unlink-cmd() {
  declare desc="unlink the $PLUGIN_SERVICE service from the app"
  local cmd="$PLUGIN_COMMAND_PREFIX:unlink" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1

  "${DOKKU_LIB_ROOT}/data/${PLUGIN_COMMAND_PREFIX}/dokku-datastore" unlink "$PLUGIN_COMMAND_PREFIX" "$@"
}

service-unlink-cmd "$@"
