#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_BASE_PATH/common/functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/functions"

service-unlink-cmd() {
  #E you can unlink a $PLUGIN_COMMAND_PREFIX service
  #E > NOTE: this will restart your app and unset related environment variables
  #E dokku $PLUGIN_COMMAND_PREFIX:unlink lolipop playground
  #A service, service to run command against
  #A app, app to run command against
  declare desc="unlink the $PLUGIN_SERVICE service from the app"
  local cmd="$PLUGIN_COMMAND_PREFIX:unlink" argv=("$@"); [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare SERVICE="$1" APP="$2"
  APP=${APP:="$DOKKU_APP_NAME"}

  local USER=''

  local next_index=1; local skip=false; local args=("$@"); local positional=()
  for arg in "$@"; do
    $skip && skip=false && local next_index=$(( next_index + 1 )) && continue
    case "$arg" in
      --database)
        DATABASE=${args[$next_index]}; skip=true
        ;;
      *)
        positional+=("$arg")
    esac
    local next_index=$(( next_index + 1 ))
  done

  declare SERVICE="${positional[0]}" APP="${positional[1]}"

  [[ -z "$SERVICE" ]] && dokku_log_fail "Please specify a name for the service"
  [[ -z "$APP" ]] && dokku_log_fail "Please specify an app to run the command on"
  verify_service_name "$SERVICE"
  verify_app_name "$APP"
  [[ -z "$DATABASE" ]] || verify_database_name "$SERVICE" "$DATABASE"
  service_unlink "$SERVICE" "$APP" "$DATABASE"

}

service-unlink-cmd "$@"
