#!/bin/bash
set -eo pipefail

log-info() {
  declare desc="Log info formatter"
  echo "    $*" 1>&2
}

log-fail() {
  declare desc="Log fail formatter"
  echo "!   $*" 1>&2
  exit 1
}

main() {
  dokku plugin:install

  # built in the Dockerfile
  PLUGIN_NAME="$(source /tmp/.env && echo "$PLUGIN_NAME")"
  PLUGIN_VARIABLE="$(source /tmp/.env && echo "$PLUGIN_VARIABLE")"
  echo "export ${PLUGIN_VARIABLE}_HOST_ROOT=${SERVICE_HOST_ROOT}/$PLUGIN_NAME" > /etc/default/dokku
}

main "$@"